from conftest import *
from pages.school_registration_page import *

def test_school_registration_valid_data(driver):
    school_registration_page = SchoolRegistrationPage(driver)
    main_page = MainPage(driver)

    main_page.go_to_school_registration()
    school_registration_page.fill_valid_school_name()
    school_registration_page.fill_valid_school_street()
    school_registration_page.fill_valid_school_building_number()
    school_registration_page.fill_valid_school_postal_code()
    school_registration_page.fill_valid_school_city()
    school_registration_page.fill_valid_school_nip()
    school_registration_page.fill_valid_school_regon()
    school_registration_page.fill_valid_school_website()
    school_registration_page.fill_valid_school_submitter_name()
    school_registration_page.fill_valid_school_submitter_role()
    school_registration_page.fill_valid_school_contact_phone()
    school_registration_page.fill_valid_school_contact_email()
    school_registration_page.accept_school_terms()
    school_registration_page.accept_school_gdpr()
    school_registration_page.click_on_voivodeship()
    school_registration_page.choose_voivodeship()
    school_registration_page.submit_school_registration()
    assert school_registration_page.school_error() is False

def test_school_registration_invalid_postal_code(driver):
    school_registration_page = SchoolRegistrationPage(driver)
    main_page = MainPage(driver)

    main_page.go_to_school_registration()
    school_registration_page.fill_valid_school_name()
    school_registration_page.fill_valid_school_street()
    school_registration_page.fill_valid_school_building_number()
    school_registration_page.fill_invalid_school_postal_code()
    school_registration_page.fill_valid_school_city()
    school_registration_page.fill_valid_school_nip()
    school_registration_page.fill_valid_school_regon()
    school_registration_page.fill_valid_school_website()
    school_registration_page.fill_valid_school_submitter_name()
    school_registration_page.fill_valid_school_submitter_role()
    school_registration_page.fill_valid_school_contact_phone()
    school_registration_page.fill_valid_school_contact_email()
    school_registration_page.accept_school_terms()
    school_registration_page.accept_school_gdpr()
    school_registration_page.click_on_voivodeship()
    school_registration_page.choose_voivodeship()
    assert school_registration_page.assert_input_length() is True

def test_school_registration_invalid_nip(driver):
    school_registration_page = SchoolRegistrationPage(driver)
    main_page = MainPage(driver)

    main_page.go_to_school_registration()
    school_registration_page.fill_valid_school_name()
    school_registration_page.fill_valid_school_street()
    school_registration_page.fill_valid_school_building_number()
    school_registration_page.fill_valid_school_postal_code()
    school_registration_page.fill_valid_school_city()
    school_registration_page.fill_invalid_school_nip()
    school_registration_page.fill_valid_school_regon()
    school_registration_page.fill_valid_school_website()
    school_registration_page.fill_valid_school_submitter_name()
    school_registration_page.fill_valid_school_submitter_role()
    school_registration_page.fill_valid_school_contact_phone()
    school_registration_page.fill_valid_school_contact_email()
    school_registration_page.accept_school_terms()
    school_registration_page.accept_school_gdpr()
    school_registration_page.click_on_voivodeship()
    school_registration_page.choose_voivodeship()
    assert school_registration_page.school_error() is not True

def test_school_registration_invalid_letters_nip(driver):
    school_registration_page = SchoolRegistrationPage(driver)
    main_page = MainPage(driver)

    main_page.go_to_school_registration()
    school_registration_page.fill_valid_school_name()
    school_registration_page.fill_valid_school_street()
    school_registration_page.fill_valid_school_building_number()
    school_registration_page.fill_valid_school_postal_code()
    school_registration_page.fill_valid_school_city()
    school_registration_page.fill_invalid_letters_school_nip()
    school_registration_page.fill_valid_school_regon()
    school_registration_page.fill_valid_school_website()
    school_registration_page.fill_valid_school_submitter_name()
    school_registration_page.fill_valid_school_submitter_role()
    school_registration_page.fill_valid_school_contact_phone()
    school_registration_page.fill_valid_school_contact_email()
    school_registration_page.accept_school_terms()
    school_registration_page.accept_school_gdpr()
    school_registration_page.click_on_voivodeship()
    school_registration_page.choose_voivodeship()
    assert school_registration_page.school_error() is not True

def test_school_registration_invalid_regon(driver):
    school_registration_page = SchoolRegistrationPage(driver)
    main_page = MainPage(driver)

    main_page.go_to_school_registration()
    school_registration_page.fill_valid_school_name()
    school_registration_page.fill_valid_school_street()
    school_registration_page.fill_valid_school_building_number()
    school_registration_page.fill_valid_school_postal_code()
    school_registration_page.fill_valid_school_city()
    school_registration_page.fill_valid_school_nip()
    school_registration_page.fill_invalid_school_regon()
    school_registration_page.fill_valid_school_website()
    school_registration_page.fill_valid_school_submitter_name()
    school_registration_page.fill_valid_school_submitter_role()
    school_registration_page.fill_valid_school_contact_phone()
    school_registration_page.fill_valid_school_contact_email()
    school_registration_page.accept_school_terms()
    school_registration_page.accept_school_gdpr()
    school_registration_page.click_on_voivodeship()
    school_registration_page.choose_voivodeship()
    assert school_registration_page.school_error() is not True

def test_school_registration_invalid_letters_regon(driver):
    school_registration_page = SchoolRegistrationPage(driver)
    main_page = MainPage(driver)

    main_page.go_to_school_registration()
    school_registration_page.fill_valid_school_name()
    school_registration_page.fill_valid_school_street()
    school_registration_page.fill_valid_school_building_number()
    school_registration_page.fill_valid_school_postal_code()
    school_registration_page.fill_valid_school_city()
    school_registration_page.fill_valid_school_nip()
    school_registration_page.fill_invalid_letters_school_regon()
    school_registration_page.fill_valid_school_website()
    school_registration_page.fill_valid_school_submitter_name()
    school_registration_page.fill_valid_school_submitter_role()
    school_registration_page.fill_valid_school_contact_phone()
    school_registration_page.fill_valid_school_contact_email()
    school_registration_page.accept_school_terms()
    school_registration_page.accept_school_gdpr()
    school_registration_page.click_on_voivodeship()
    school_registration_page.choose_voivodeship()
    assert school_registration_page.school_error() is not True

def test_school_registration_invalid_special_email(driver):
    school_registration_page = SchoolRegistrationPage(driver)
    main_page = MainPage(driver)

    main_page.go_to_school_registration()
    school_registration_page.fill_valid_school_name()
    school_registration_page.fill_valid_school_street()
    school_registration_page.fill_valid_school_building_number()
    school_registration_page.fill_valid_school_postal_code()
    school_registration_page.fill_valid_school_city()
    school_registration_page.fill_valid_school_nip()
    school_registration_page.fill_valid_school_regon()
    school_registration_page.fill_valid_school_website()
    school_registration_page.fill_valid_school_submitter_name()
    school_registration_page.fill_valid_school_submitter_role()
    school_registration_page.fill_valid_school_contact_phone()
    school_registration_page.fill_special_school_contact_email()
    school_registration_page.accept_school_terms()
    school_registration_page.accept_school_gdpr()
    school_registration_page.click_on_voivodeship()
    school_registration_page.choose_voivodeship()
    assert school_registration_page.school_error() is not True

def test_school_registration_invalid_no_domain_email(driver):
    school_registration_page = SchoolRegistrationPage(driver)
    main_page = MainPage(driver)

    main_page.go_to_school_registration()
    school_registration_page.fill_valid_school_name()
    school_registration_page.fill_valid_school_street()
    school_registration_page.fill_valid_school_building_number()
    school_registration_page.fill_valid_school_postal_code()
    school_registration_page.fill_valid_school_city()
    school_registration_page.fill_valid_school_nip()
    school_registration_page.fill_valid_school_regon()
    school_registration_page.fill_valid_school_website()
    school_registration_page.fill_valid_school_submitter_name()
    school_registration_page.fill_valid_school_submitter_role()
    school_registration_page.fill_valid_school_contact_phone()
    school_registration_page.fill_no_domain_school_contact_email()
    school_registration_page.accept_school_terms()
    school_registration_page.accept_school_gdpr()
    school_registration_page.click_on_voivodeship()
    school_registration_page.choose_voivodeship()
    assert school_registration_page.school_error() is not True

def test_school_registration_invalid_double_at_email(driver):
    school_registration_page = SchoolRegistrationPage(driver)
    main_page = MainPage(driver)

    main_page.go_to_school_registration()
    school_registration_page.fill_valid_school_name()
    school_registration_page.fill_valid_school_street()
    school_registration_page.fill_valid_school_building_number()
    school_registration_page.fill_valid_school_postal_code()
    school_registration_page.fill_valid_school_city()
    school_registration_page.fill_valid_school_nip()
    school_registration_page.fill_valid_school_regon()
    school_registration_page.fill_valid_school_website()
    school_registration_page.fill_valid_school_submitter_name()
    school_registration_page.fill_valid_school_submitter_role()
    school_registration_page.fill_valid_school_contact_phone()
    school_registration_page.fill_double_at_school_contact_email()
    school_registration_page.accept_school_terms()
    school_registration_page.accept_school_gdpr()
    school_registration_page.click_on_voivodeship()
    school_registration_page.choose_voivodeship()
    assert school_registration_page.school_error() is not True

def test_school_registration_invalid_without_at_email(driver):
    school_registration_page = SchoolRegistrationPage(driver)
    main_page = MainPage(driver)

    main_page.go_to_school_registration()
    school_registration_page.fill_valid_school_name()
    school_registration_page.fill_valid_school_street()
    school_registration_page.fill_valid_school_building_number()
    school_registration_page.fill_valid_school_postal_code()
    school_registration_page.fill_valid_school_city()
    school_registration_page.fill_valid_school_nip()
    school_registration_page.fill_valid_school_regon()
    school_registration_page.fill_valid_school_website()
    school_registration_page.fill_valid_school_submitter_name()
    school_registration_page.fill_valid_school_submitter_role()
    school_registration_page.fill_valid_school_contact_phone()
    school_registration_page.fill_without_at_school_contact_email()
    school_registration_page.accept_school_terms()
    school_registration_page.accept_school_gdpr()
    school_registration_page.click_on_voivodeship()
    school_registration_page.choose_voivodeship()
    assert school_registration_page.school_error() is not True

def test_school_registration_no_accepted_terms(driver):
    school_registration_page = SchoolRegistrationPage(driver)
    main_page = MainPage(driver)

    main_page.go_to_school_registration()
    school_registration_page.fill_valid_school_name()
    school_registration_page.fill_valid_school_street()
    school_registration_page.fill_valid_school_building_number()
    school_registration_page.fill_valid_school_postal_code()
    school_registration_page.fill_valid_school_city()
    school_registration_page.fill_valid_school_nip()
    school_registration_page.fill_valid_school_regon()
    school_registration_page.fill_valid_school_website()
    school_registration_page.fill_valid_school_submitter_name()
    school_registration_page.fill_valid_school_submitter_role()
    school_registration_page.fill_valid_school_contact_phone()
    school_registration_page.fill_valid_school_contact_email()
    school_registration_page.accept_school_gdpr()
    school_registration_page.submit_school_registration()
    assert school_registration_page.school_error() is not True

def test_school_registration_no_accepted_gdpr(driver):
    school_registration_page = SchoolRegistrationPage(driver)
    main_page = MainPage(driver)

    main_page.go_to_school_registration()
    school_registration_page.fill_valid_school_name()
    school_registration_page.fill_valid_school_street()
    school_registration_page.fill_valid_school_building_number()
    school_registration_page.fill_valid_school_postal_code()
    school_registration_page.fill_valid_school_city()
    school_registration_page.fill_valid_school_nip()
    school_registration_page.fill_valid_school_regon()
    school_registration_page.fill_valid_school_website()
    school_registration_page.fill_valid_school_submitter_name()
    school_registration_page.fill_valid_school_submitter_role()
    school_registration_page.fill_valid_school_contact_phone()
    school_registration_page.fill_valid_school_contact_email()
    school_registration_page.accept_school_terms()
    school_registration_page.submit_school_registration()
    assert school_registration_page.school_error() is not True

def test_school_registration_invalid_contact_phone(driver):
    school_registration_page = SchoolRegistrationPage(driver)
    main_page = MainPage(driver)

    main_page.go_to_school_registration()
    school_registration_page.fill_valid_school_name()
    school_registration_page.fill_valid_school_street()
    school_registration_page.fill_valid_school_building_number()
    school_registration_page.fill_valid_school_postal_code()
    school_registration_page.fill_valid_school_city()
    school_registration_page.fill_valid_school_nip()
    school_registration_page.fill_valid_school_regon()
    school_registration_page.fill_valid_school_website()
    school_registration_page.fill_valid_school_submitter_name()
    school_registration_page.fill_valid_school_submitter_role()
    school_registration_page.fill_invalid_school_contact_phone()
    school_registration_page.fill_valid_school_contact_email()
    school_registration_page.accept_school_terms()
    school_registration_page.accept_school_gdpr()
    school_registration_page.submit_school_registration()
    assert school_registration_page.school_error() is not True

def test_school_registration_empty_fields(driver):
    school_registration_page = SchoolRegistrationPage(driver)
    main_page = MainPage(driver)

    main_page.go_to_school_registration()
    school_registration_page.submit_school_registration()
    assert school_registration_page.school_error() is not True